# Site settings
title: flatpak
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fixme.org" # the base hostname & protocol for your site
sourceurl: "https://github.com/flatpak/flatpak.github.io"
description: "The Future of Apps on Linux"

permalink: /:title/

# Build settings
markdown: kramdown
